---
   ###UBUNTU
  ###UBUNTU
  ###UBUNTU
- name: Install Logstash (Ubuntu)
  apt:
    name: logstash
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  
- name: Run daemon-reload for logstash (Ubuntu)
  systemd: daemon_reload=yes
  when: ansible_distribution == "Ubuntu"
  
- name: Enable service logstash (Ubuntu)
  systemd:
    name: logstash
    enabled: yes
  when: ansible_distribution == "Ubuntu"
  
- name: ensure logstash is running (Ubuntu)
  systemd: state=started name=logstash
  when: ansible_distribution == "Ubuntu"

# Install/run logstash
###CENTOS
###CENTOS

- name: Install Logstash CentOs
  dnf:
    name: logstash
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Run daemon-reload for logstash for CentOs
  systemd: daemon_reload=yes
  when: ansible_distribution == "Ubuntu"

- name: Enable service logstash for CentOs
  systemd:
    name: logstash
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: ensure logstash is running for CentOs
  systemd: state=started name=logstash
  when: ansible_distribution == "CentOS"

