---

- name: install required packages
  apt:
    name:
      - gnupg2
      - curl
      - software-properties-common
    state: present
  when: ansible_distribution == "Ubuntu"

#- name: Add the Grafana GPG key and APT repository
#  shell: |
#    curl https://packages.grafana.com/gpg.key | sudo apt-key add -
#    add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
#  args:
#    warn: no
#  when: ansible_distribution == "Ubuntu"

- name: Install the grafana pckg
  apt:
    name: grafana-server
    state: present
    update_cache: yes
  notify:
    - Start grafana
    - Enable grafana
  when: ansible_distribution == "Ubuntu"
   
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
  notify: Start and Enable Nginx
  when: ansible_distribution == "Ubuntu"
  
- name: Create grafana nginx config file
  copy:
      dest: /etc/nginx/conf.d/grafana.conf
      mode: 0755
      content: |
        server {
          listen 80;
          server_tokens off;
          client_max_body_size 10M;
          server_name grafana.citizix.com;

          ignore_invalid_headers off;

          if ($host !~* ^(grafana.citizix.com)$ ) {
              return 444;
          }

          location / {
              send_timeout            600;
              proxy_read_timeout      600;
              proxy_send_timeout      600;
              proxy_connect_timeout   600;
              proxy_redirect          off;
              proxy_set_header        Host $host;
              proxy_set_header        X-Real-IP $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header        X-Forwarded-Host $server_name;
              proxy_set_header        X-Forwarded-Proto $scheme;
              proxy_pass http://127.0.0.1:3000;
          }
        }
  when: ansible_distribution == "Ubuntu"
  
- name: Start grafana
  systemd:
    name: grafana-server
    state: started
  when: ansible_distribution == "Ubuntu"
  
- name: Enable grafana
  systemd:
    name: grafana-server
    enabled: yes
  when: ansible_distribution == "Ubuntu"
  
- name: Start and Enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"
